version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: employees
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10
  app:
    image: py-flask
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - appnet
    links: 
      - db
    depends_on: 
      db:
        condition: service_healthy  
networks:
  appnet:
    driver: bridge